#person:
#  name: zl
#  age: 18
#  isMan: true
#  birth: 1994/10/18
#  maps: {k1: map1,k2: map2}
#  lists:
#    -zl1
#    -zl2
#  student:
#    name: zlray
#    age: 24

#多个文档块
#server:
#  port: 8080
#spring:
#  profiles:
#    active: prod
#---
#server:
#  port: 8081
#spring:
#  profiles: dev
#---
#server:
#  port: 8082
#spring:
#  profiles: prod

